let xAxisData=[
    {
        "name":"jan",
        "sale":112_000
    },
    {
        "name":"feb",
        "sale":99_000
    },
    {
        "name":"mar",
        "sale":12_000
    },
    {
        "name":"apr",
        "sale":99_000
    },
    {
        "name":"may",
        "sale":54_000
    },
    {
        "name":"jun",
        "sale":85_000
    },
    {
        "name":"jul",
        "sale":34_000
    },
    {
        "name":"agu",
        "sale":18_000
    },
    {
        "name":"sep",
        "sale":0
    },
    {
        "name":"oct",
        "sale":73_000
    },
    {
        "name":"nov",
        "sale":12_000
    },
    {
        "name":"dec",
        "sale":97_000
    }
]

let newMembers=[
    {
        id:1,
        username:'alberto',
        title:'web dev',
        img:'images/wer.webp'
    },
    {
        id:2,
        username:'albto',
        title:'dev',
        img:'images/wer.webp'
    },
    {
        id:3,
        username:'alto',
        title:'web',
        img:'images/wer.webp'
    },
    {
        id:4,
        username:'rdsdsto',
        title:'web dev',
        img:'images/wer.webp'
    },
]

let userRows=[
    {
        id:1,
        username:'alberto',
        avatar:'images/wer.webp',
        status:'active',
        transaction:'$129.99',
        email:'xyz@gmail.com'
    },
    {
        id:2,
        username:'alberto',
        avatar:'images/wer.webp',
        status:'active',
        transaction:'$129.99',
        email:'xyz@gmail.com'
    },
    {
        id:3,
        username:'alberto',
        avatar:'images/wer.webp',
        status:'active',
        transaction:'$129.99',
        email:'xyz@gmail.com'
    },
    {
        id:4,
        username:'alberto',
        avatar:'images/wer.webp',
        status:'active',
        transaction:'$129.99',
        email:'xyz@gmail.com'
    },
    {
        id:5,
        username:'alberto',
        avatar:'images/wer.webp',
        status:'active',
        transaction:'$129.99',
        email:'xyz@gmail.com'
    },
    {
        id:6,
        username:'alberto',
        avatar:'images/wer.webp',
        status:'active',
        transaction:'$129.99',
        email:'xyz@gmail.com'
    },
    {
        id:7,
        username:'alberto',
        avatar:'images/wer.webp',
        status:'active',
        transaction:'$129.99',
        email:'xyz@gmail.com'
    },
]
export {xAxisData , newMembers, userRows}